version: '3.1'

services:
  dbmysql:
    image: mysql:8.3
    container_name: mysql-container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      - ./mysql-data:/var/lib/mysql
    user: "1001:1001" # change 1001 bằng UID và GID của user ngochv - id ngochv
volumes:
  mysql-data: 
